/home/jczn2/.conda/envs/yibo/bin/python main_fed.py --dataset cifar --distribution noniid --alpha 0.5 --random_cost mild_label_correlated_hierarchical --num_users 100 --concurrency 40 --buffer_size 10 --model resnet --total_rounds 150 --local_bs 100 --local_period 10 --interval 1 --lr 0.003 --algo FedBuff --seed 100 --output_dir /home/jczn2/DirBridge_state/e1_runs/cifar/acc --system_metrics_log_dir /home/jczn2/DirBridge_state/e1_runs/cifar/metrics --run_tag e1_dev_fedbuff_t01 --gpu 0
/home/jczn2/.conda/envs/yibo/bin/python main_fed.py --dataset cifar --distribution noniid --alpha 0.5 --random_cost mild_label_correlated_hierarchical --num_users 100 --concurrency 40 --buffer_size 10 --model resnet --total_rounds 150 --local_bs 50 --local_period 10 --interval 1 --lr 0.003 --algo FedBuff --seed 100 --output_dir /home/jczn2/DirBridge_state/e1_runs/cifar/acc --system_metrics_log_dir /home/jczn2/DirBridge_state/e1_runs/cifar/metrics --run_tag e1_dev_fedbuff_t02 --gpu 0
/home/jczn2/.conda/envs/yibo/bin/python main_fed.py --dataset cifar --distribution noniid --alpha 0.5 --random_cost mild_label_correlated_hierarchical --num_users 100 --concurrency 40 --buffer_size 10 --model resnet --total_rounds 150 --local_bs 100 --local_period 10 --interval 1 --lr 0.01 --algo FedBuff --seed 100 --output_dir /home/jczn2/DirBridge_state/e1_runs/cifar/acc --system_metrics_log_dir /home/jczn2/DirBridge_state/e1_runs/cifar/metrics --run_tag e1_dev_fedbuff_t03 --gpu 0
/home/jczn2/.conda/envs/yibo/bin/python main_fed.py --dataset cifar --distribution noniid --alpha 0.5 --random_cost mild_label_correlated_hierarchical --num_users 100 --concurrency 40 --buffer_size 10 --model resnet --total_rounds 150 --local_bs 50 --local_period 10 --interval 1 --lr 0.01 --algo FedBuff --seed 100 --output_dir /home/jczn2/DirBridge_state/e1_runs/cifar/acc --system_metrics_log_dir /home/jczn2/DirBridge_state/e1_runs/cifar/metrics --run_tag e1_dev_fedbuff_t04 --gpu 0
/home/jczn2/.conda/envs/yibo/bin/python main_fed.py --dataset cifar --distribution noniid --alpha 0.5 --random_cost mild_label_correlated_hierarchical --num_users 100 --concurrency 40 --buffer_size 10 --model resnet --total_rounds 150 --local_bs 100 --local_period 10 --interval 1 --lr 0.03 --algo FedBuff --seed 100 --output_dir /home/jczn2/DirBridge_state/e1_runs/cifar/acc --system_metrics_log_dir /home/jczn2/DirBridge_state/e1_runs/cifar/metrics --run_tag e1_dev_fedbuff_t05 --gpu 0
/home/jczn2/.conda/envs/yibo/bin/python main_fed.py --dataset cifar --distribution noniid --alpha 0.5 --random_cost mild_label_correlated_hierarchical --num_users 100 --concurrency 40 --buffer_size 10 --model resnet --total_rounds 150 --local_bs 50 --local_period 10 --interval 1 --lr 0.03 --algo FedBuff --seed 100 --output_dir /home/jczn2/DirBridge_state/e1_runs/cifar/acc --system_metrics_log_dir /home/jczn2/DirBridge_state/e1_runs/cifar/metrics --run_tag e1_dev_fedbuff_t06 --gpu 0
/home/jczn2/.conda/envs/yibo/bin/python main_fed.py --dataset cifar --distribution noniid --alpha 0.5 --random_cost mild_label_correlated_hierarchical --num_users 100 --concurrency 40 --buffer_size 10 --model resnet --total_rounds 150 --local_bs 100 --local_period 10 --interval 1 --lr 0.05 --algo FedBuff --seed 100 --output_dir /home/jczn2/DirBridge_state/e1_runs/cifar/acc --system_metrics_log_dir /home/jczn2/DirBridge_state/e1_runs/cifar/metrics --run_tag e1_dev_fedbuff_t07 --gpu 0
/home/jczn2/.conda/envs/yibo/bin/python main_fed.py --dataset cifar --distribution noniid --alpha 0.5 --random_cost mild_label_correlated_hierarchical --num_users 100 --concurrency 40 --buffer_size 10 --model resnet --total_rounds 150 --local_bs 50 --local_period 10 --interval 1 --lr 0.05 --algo FedBuff --seed 100 --output_dir /home/jczn2/DirBridge_state/e1_runs/cifar/acc --system_metrics_log_dir /home/jczn2/DirBridge_state/e1_runs/cifar/metrics --run_tag e1_dev_fedbuff_t08 --gpu 0
/home/jczn2/.conda/envs/yibo/bin/python main_fed.py --dataset cifar --distribution noniid --alpha 0.5 --random_cost mild_label_correlated_hierarchical --num_users 100 --concurrency 40 --buffer_size 10 --model resnet --total_rounds 150 --local_bs 100 --local_period 10 --interval 1 --lr 0.1 --algo FedBuff --seed 100 --output_dir /home/jczn2/DirBridge_state/e1_runs/cifar/acc --system_metrics_log_dir /home/jczn2/DirBridge_state/e1_runs/cifar/metrics --run_tag e1_dev_fedbuff_t09 --gpu 0
/home/jczn2/.conda/envs/yibo/bin/python main_fed.py --dataset cifar --distribution noniid --alpha 0.5 --random_cost mild_label_correlated_hierarchical --num_users 100 --concurrency 40 --buffer_size 10 --model resnet --total_rounds 150 --local_bs 50 --local_period 10 --interval 1 --lr 0.1 --algo FedBuff --seed 100 --output_dir /home/jczn2/DirBridge_state/e1_runs/cifar/acc --system_metrics_log_dir /home/jczn2/DirBridge_state/e1_runs/cifar/metrics --run_tag e1_dev_fedbuff_t10 --gpu 0
/home/jczn2/.conda/envs/yibo/bin/python main_fed.py --dataset cifar --distribution noniid --alpha 0.5 --random_cost mild_label_correlated_hierarchical --num_users 100 --concurrency 40 --buffer_size 10 --model resnet --total_rounds 150 --local_bs 100 --local_period 20 --interval 1 --lr 0.005 --algo FedBuff --seed 100 --output_dir /home/jczn2/DirBridge_state/e1_runs/cifar/acc --system_metrics_log_dir /home/jczn2/DirBridge_state/e1_runs/cifar/metrics --run_tag e1_dev_fedbuff_t11 --gpu 0
/home/jczn2/.conda/envs/yibo/bin/python main_fed.py --dataset cifar --distribution noniid --alpha 0.5 --random_cost mild_label_correlated_hierarchical --num_users 100 --concurrency 40 --buffer_size 10 --model resnet --total_rounds 150 --local_bs 50 --local_period 20 --interval 1 --lr 0.005 --algo FedBuff --seed 100 --output_dir /home/jczn2/DirBridge_state/e1_runs/cifar/acc --system_metrics_log_dir /home/jczn2/DirBridge_state/e1_runs/cifar/metrics --run_tag e1_dev_fedbuff_t12 --gpu 0
/home/jczn2/.conda/envs/yibo/bin/python main_fed.py --dataset cifar --distribution noniid --alpha 0.5 --random_cost mild_label_correlated_hierarchical --num_users 100 --concurrency 40 --buffer_size 10 --model resnet --total_rounds 150 --local_bs 100 --local_period 10 --interval 1 --lr 0.005 --algo FedBuff --seed 100 --output_dir /home/jczn2/DirBridge_state/e1_runs/cifar/acc --system_metrics_log_dir /home/jczn2/DirBridge_state/e1_runs/cifar/metrics --run_tag e1_dev_fedbuff_t13 --gpu 0
/home/jczn2/.conda/envs/yibo/bin/python main_fed.py --dataset cifar --distribution noniid --alpha 0.5 --random_cost mild_label_correlated_hierarchical --num_users 100 --concurrency 40 --buffer_size 10 --model resnet --total_rounds 150 --local_bs 50 --local_period 10 --interval 1 --lr 0.005 --algo FedBuff --seed 100 --output_dir /home/jczn2/DirBridge_state/e1_runs/cifar/acc --system_metrics_log_dir /home/jczn2/DirBridge_state/e1_runs/cifar/metrics --run_tag e1_dev_fedbuff_t14 --gpu 0
/home/jczn2/.conda/envs/yibo/bin/python main_fed.py --dataset cifar --distribution noniid --alpha 0.5 --random_cost mild_label_correlated_hierarchical --num_users 100 --concurrency 40 --buffer_size 10 --model resnet --total_rounds 150 --local_bs 100 --local_period 20 --interval 1 --lr 0.02 --algo FedBuff --seed 100 --output_dir /home/jczn2/DirBridge_state/e1_runs/cifar/acc --system_metrics_log_dir /home/jczn2/DirBridge_state/e1_runs/cifar/metrics --run_tag e1_dev_fedbuff_t15 --gpu 0
/home/jczn2/.conda/envs/yibo/bin/python main_fed.py --dataset cifar --distribution noniid --alpha 0.5 --random_cost mild_label_correlated_hierarchical --num_users 100 --concurrency 40 --buffer_size 10 --model resnet --total_rounds 150 --local_bs 50 --local_period 20 --interval 1 --lr 0.02 --algo FedBuff --seed 100 --output_dir /home/jczn2/DirBridge_state/e1_runs/cifar/acc --system_metrics_log_dir /home/jczn2/DirBridge_state/e1_runs/cifar/metrics --run_tag e1_dev_fedbuff_t16 --gpu 0
/home/jczn2/.conda/envs/yibo/bin/python main_fed.py --dataset cifar --distribution noniid --alpha 0.5 --random_cost mild_label_correlated_hierarchical --num_users 100 --concurrency 40 --buffer_size 10 --model resnet --total_rounds 150 --local_bs 100 --local_period 10 --interval 1 --lr 0.02 --algo FedBuff --seed 100 --output_dir /home/jczn2/DirBridge_state/e1_runs/cifar/acc --system_metrics_log_dir /home/jczn2/DirBridge_state/e1_runs/cifar/metrics --run_tag e1_dev_fedbuff_t17 --gpu 0
/home/jczn2/.conda/envs/yibo/bin/python main_fed.py --dataset cifar --distribution noniid --alpha 0.5 --random_cost mild_label_correlated_hierarchical --num_users 100 --concurrency 40 --buffer_size 10 --model resnet --total_rounds 150 --local_bs 50 --local_period 10 --interval 1 --lr 0.02 --algo FedBuff --seed 100 --output_dir /home/jczn2/DirBridge_state/e1_runs/cifar/acc --system_metrics_log_dir /home/jczn2/DirBridge_state/e1_runs/cifar/metrics --run_tag e1_dev_fedbuff_t18 --gpu 0
/home/jczn2/.conda/envs/yibo/bin/python main_fed.py --dataset cifar --distribution noniid --alpha 0.5 --random_cost mild_label_correlated_hierarchical --num_users 100 --concurrency 40 --buffer_size 10 --model resnet --total_rounds 150 --local_bs 100 --local_period 20 --interval 1 --lr 0.003 --algo FedBuff --seed 100 --output_dir /home/jczn2/DirBridge_state/e1_runs/cifar/acc --system_metrics_log_dir /home/jczn2/DirBridge_state/e1_runs/cifar/metrics --run_tag e1_dev_fedbuff_t19 --gpu 0
/home/jczn2/.conda/envs/yibo/bin/python main_fed.py --dataset cifar --distribution noniid --alpha 0.5 --random_cost mild_label_correlated_hierarchical --num_users 100 --concurrency 40 --buffer_size 10 --model resnet --total_rounds 150 --local_bs 50 --local_period 20 --interval 1 --lr 0.1 --algo FedBuff --seed 100 --output_dir /home/jczn2/DirBridge_state/e1_runs/cifar/acc --system_metrics_log_dir /home/jczn2/DirBridge_state/e1_runs/cifar/metrics --run_tag e1_dev_fedbuff_t20 --gpu 0
/home/jczn2/.conda/envs/yibo/bin/python main_fed.py --dataset cifar --distribution noniid --alpha 0.5 --random_cost mild_label_correlated_hierarchical --num_users 100 --concurrency 40 --buffer_size 10 --model resnet --total_rounds 150 --local_bs 100 --local_period 10 --interval 1 --lr 0.003 --algo CA2FL --seed 100 --output_dir /home/jczn2/DirBridge_state/e1_runs/cifar/acc --system_metrics_log_dir /home/jczn2/DirBridge_state/e1_runs/cifar/metrics --run_tag e1_dev_ca2fl_t01 --global_lr 1.0 --gpu 0
/home/jczn2/.conda/envs/yibo/bin/python main_fed.py --dataset cifar --distribution noniid --alpha 0.5 --random_cost mild_label_correlated_hierarchical --num_users 100 --concurrency 40 --buffer_size 10 --model resnet --total_rounds 150 --local_bs 100 --local_period 10 --interval 1 --lr 0.003 --algo CA2FL --seed 100 --output_dir /home/jczn2/DirBridge_state/e1_runs/cifar/acc --system_metrics_log_dir /home/jczn2/DirBridge_state/e1_runs/cifar/metrics --run_tag e1_dev_ca2fl_t02 --global_lr 0.5 --gpu 0
/home/jczn2/.conda/envs/yibo/bin/python main_fed.py --dataset cifar --distribution noniid --alpha 0.5 --random_cost mild_label_correlated_hierarchical --num_users 100 --concurrency 40 --buffer_size 10 --model resnet --total_rounds 150 --local_bs 100 --local_period 10 --interval 1 --lr 0.003 --algo CA2FL --seed 100 --output_dir /home/jczn2/DirBridge_state/e1_runs/cifar/acc --system_metrics_log_dir /home/jczn2/DirBridge_state/e1_runs/cifar/metrics --run_tag e1_dev_ca2fl_t03 --global_lr 0.1 --gpu 0
/home/jczn2/.conda/envs/yibo/bin/python main_fed.py --dataset cifar --distribution noniid --alpha 0.5 --random_cost mild_label_correlated_hierarchical --num_users 100 --concurrency 40 --buffer_size 10 --model resnet --total_rounds 150 --local_bs 100 --local_period 10 --interval 1 --lr 0.003 --algo CA2FL --seed 100 --output_dir /home/jczn2/DirBridge_state/e1_runs/cifar/acc --system_metrics_log_dir /home/jczn2/DirBridge_state/e1_runs/cifar/metrics --run_tag e1_dev_ca2fl_t04 --global_lr 0.05 --gpu 0
/home/jczn2/.conda/envs/yibo/bin/python main_fed.py --dataset cifar --distribution noniid --alpha 0.5 --random_cost mild_label_correlated_hierarchical --num_users 100 --concurrency 40 --buffer_size 10 --model resnet --total_rounds 150 --local_bs 100 --local_period 10 --interval 1 --lr 0.003 --algo CA2FL --seed 100 --output_dir /home/jczn2/DirBridge_state/e1_runs/cifar/acc --system_metrics_log_dir /home/jczn2/DirBridge_state/e1_runs/cifar/metrics --run_tag e1_dev_ca2fl_t05 --global_lr 0.01 --gpu 0
/home/jczn2/.conda/envs/yibo/bin/python main_fed.py --dataset cifar --distribution noniid --alpha 0.5 --random_cost mild_label_correlated_hierarchical --num_users 100 --concurrency 40 --buffer_size 10 --model resnet --total_rounds 150 --local_bs 100 --local_period 10 --interval 1 --lr 0.01 --algo CA2FL --seed 100 --output_dir /home/jczn2/DirBridge_state/e1_runs/cifar/acc --system_metrics_log_dir /home/jczn2/DirBridge_state/e1_runs/cifar/metrics --run_tag e1_dev_ca2fl_t06 --global_lr 1.0 --gpu 0
/home/jczn2/.conda/envs/yibo/bin/python main_fed.py --dataset cifar --distribution noniid --alpha 0.5 --random_cost mild_label_correlated_hierarchical --num_users 100 --concurrency 40 --buffer_size 10 --model resnet --total_rounds 150 --local_bs 100 --local_period 10 --interval 1 --lr 0.01 --algo CA2FL --seed 100 --output_dir /home/jczn2/DirBridge_state/e1_runs/cifar/acc --system_metrics_log_dir /home/jczn2/DirBridge_state/e1_runs/cifar/metrics --run_tag e1_dev_ca2fl_t07 --global_lr 0.5 --gpu 0
/home/jczn2/.conda/envs/yibo/bin/python main_fed.py --dataset cifar --distribution noniid --alpha 0.5 --random_cost mild_label_correlated_hierarchical --num_users 100 --concurrency 40 --buffer_size 10 --model resnet --total_rounds 150 --local_bs 100 --local_period 10 --interval 1 --lr 0.01 --algo CA2FL --seed 100 --output_dir /home/jczn2/DirBridge_state/e1_runs/cifar/acc --system_metrics_log_dir /home/jczn2/DirBridge_state/e1_runs/cifar/metrics --run_tag e1_dev_ca2fl_t08 --global_lr 0.1 --gpu 0
/home/jczn2/.conda/envs/yibo/bin/python main_fed.py --dataset cifar --distribution noniid --alpha 0.5 --random_cost mild_label_correlated_hierarchical --num_users 100 --concurrency 40 --buffer_size 10 --model resnet --total_rounds 150 --local_bs 100 --local_period 10 --interval 1 --lr 0.01 --algo CA2FL --seed 100 --output_dir /home/jczn2/DirBridge_state/e1_runs/cifar/acc --system_metrics_log_dir /home/jczn2/DirBridge_state/e1_runs/cifar/metrics --run_tag e1_dev_ca2fl_t09 --global_lr 0.05 --gpu 0
/home/jczn2/.conda/envs/yibo/bin/python main_fed.py --dataset cifar --distribution noniid --alpha 0.5 --random_cost mild_label_correlated_hierarchical --num_users 100 --concurrency 40 --buffer_size 10 --model resnet --total_rounds 150 --local_bs 100 --local_period 10 --interval 1 --lr 0.01 --algo CA2FL --seed 100 --output_dir /home/jczn2/DirBridge_state/e1_runs/cifar/acc --system_metrics_log_dir /home/jczn2/DirBridge_state/e1_runs/cifar/metrics --run_tag e1_dev_ca2fl_t10 --global_lr 0.01 --gpu 0
/home/jczn2/.conda/envs/yibo/bin/python main_fed.py --dataset cifar --distribution noniid --alpha 0.5 --random_cost mild_label_correlated_hierarchical --num_users 100 --concurrency 40 --buffer_size 10 --model resnet --total_rounds 150 --local_bs 100 --local_period 10 --interval 1 --lr 0.03 --algo CA2FL --seed 100 --output_dir /home/jczn2/DirBridge_state/e1_runs/cifar/acc --system_metrics_log_dir /home/jczn2/DirBridge_state/e1_runs/cifar/metrics --run_tag e1_dev_ca2fl_t11 --global_lr 1.0 --gpu 0
/home/jczn2/.conda/envs/yibo/bin/python main_fed.py --dataset cifar --distribution noniid --alpha 0.5 --random_cost mild_label_correlated_hierarchical --num_users 100 --concurrency 40 --buffer_size 10 --model resnet --total_rounds 150 --local_bs 100 --local_period 10 --interval 1 --lr 0.03 --algo CA2FL --seed 100 --output_dir /home/jczn2/DirBridge_state/e1_runs/cifar/acc --system_metrics_log_dir /home/jczn2/DirBridge_state/e1_runs/cifar/metrics --run_tag e1_dev_ca2fl_t12 --global_lr 0.5 --gpu 0
/home/jczn2/.conda/envs/yibo/bin/python main_fed.py --dataset cifar --distribution noniid --alpha 0.5 --random_cost mild_label_correlated_hierarchical --num_users 100 --concurrency 40 --buffer_size 10 --model resnet --total_rounds 150 --local_bs 100 --local_period 10 --interval 1 --lr 0.03 --algo CA2FL --seed 100 --output_dir /home/jczn2/DirBridge_state/e1_runs/cifar/acc --system_metrics_log_dir /home/jczn2/DirBridge_state/e1_runs/cifar/metrics --run_tag e1_dev_ca2fl_t13 --global_lr 0.1 --gpu 0
/home/jczn2/.conda/envs/yibo/bin/python main_fed.py --dataset cifar --distribution noniid --alpha 0.5 --random_cost mild_label_correlated_hierarchical --num_users 100 --concurrency 40 --buffer_size 10 --model resnet --total_rounds 150 --local_bs 100 --local_period 10 --interval 1 --lr 0.03 --algo CA2FL --seed 100 --output_dir /home/jczn2/DirBridge_state/e1_runs/cifar/acc --system_metrics_log_dir /home/jczn2/DirBridge_state/e1_runs/cifar/metrics --run_tag e1_dev_ca2fl_t14 --global_lr 0.05 --gpu 0
/home/jczn2/.conda/envs/yibo/bin/python main_fed.py --dataset cifar --distribution noniid --alpha 0.5 --random_cost mild_label_correlated_hierarchical --num_users 100 --concurrency 40 --buffer_size 10 --model resnet --total_rounds 150 --local_bs 100 --local_period 10 --interval 1 --lr 0.03 --algo CA2FL --seed 100 --output_dir /home/jczn2/DirBridge_state/e1_runs/cifar/acc --system_metrics_log_dir /home/jczn2/DirBridge_state/e1_runs/cifar/metrics --run_tag e1_dev_ca2fl_t15 --global_lr 0.01 --gpu 0
/home/jczn2/.conda/envs/yibo/bin/python main_fed.py --dataset cifar --distribution noniid --alpha 0.5 --random_cost mild_label_correlated_hierarchical --num_users 100 --concurrency 40 --buffer_size 10 --model resnet --total_rounds 150 --local_bs 100 --local_period 10 --interval 1 --lr 0.05 --algo CA2FL --seed 100 --output_dir /home/jczn2/DirBridge_state/e1_runs/cifar/acc --system_metrics_log_dir /home/jczn2/DirBridge_state/e1_runs/cifar/metrics --run_tag e1_dev_ca2fl_t16 --global_lr 1.0 --gpu 0
/home/jczn2/.conda/envs/yibo/bin/python main_fed.py --dataset cifar --distribution noniid --alpha 0.5 --random_cost mild_label_correlated_hierarchical --num_users 100 --concurrency 40 --buffer_size 10 --model resnet --total_rounds 150 --local_bs 100 --local_period 10 --interval 1 --lr 0.05 --algo CA2FL --seed 100 --output_dir /home/jczn2/DirBridge_state/e1_runs/cifar/acc --system_metrics_log_dir /home/jczn2/DirBridge_state/e1_runs/cifar/metrics --run_tag e1_dev_ca2fl_t17 --global_lr 0.5 --gpu 0
/home/jczn2/.conda/envs/yibo/bin/python main_fed.py --dataset cifar --distribution noniid --alpha 0.5 --random_cost mild_label_correlated_hierarchical --num_users 100 --concurrency 40 --buffer_size 10 --model resnet --total_rounds 150 --local_bs 100 --local_period 10 --interval 1 --lr 0.05 --algo CA2FL --seed 100 --output_dir /home/jczn2/DirBridge_state/e1_runs/cifar/acc --system_metrics_log_dir /home/jczn2/DirBridge_state/e1_runs/cifar/metrics --run_tag e1_dev_ca2fl_t18 --global_lr 0.1 --gpu 0
/home/jczn2/.conda/envs/yibo/bin/python main_fed.py --dataset cifar --distribution noniid --alpha 0.5 --random_cost mild_label_correlated_hierarchical --num_users 100 --concurrency 40 --buffer_size 10 --model resnet --total_rounds 150 --local_bs 100 --local_period 10 --interval 1 --lr 0.05 --algo CA2FL --seed 100 --output_dir /home/jczn2/DirBridge_state/e1_runs/cifar/acc --system_metrics_log_dir /home/jczn2/DirBridge_state/e1_runs/cifar/metrics --run_tag e1_dev_ca2fl_t19 --global_lr 0.05 --gpu 0
/home/jczn2/.conda/envs/yibo/bin/python main_fed.py --dataset cifar --distribution noniid --alpha 0.5 --random_cost mild_label_correlated_hierarchical --num_users 100 --concurrency 40 --buffer_size 10 --model resnet --total_rounds 150 --local_bs 100 --local_period 10 --interval 1 --lr 0.05 --algo CA2FL --seed 100 --output_dir /home/jczn2/DirBridge_state/e1_runs/cifar/acc --system_metrics_log_dir /home/jczn2/DirBridge_state/e1_runs/cifar/metrics --run_tag e1_dev_ca2fl_t20 --global_lr 0.01 --gpu 0
/home/jczn2/.conda/envs/yibo/bin/python main_fed.py --dataset cifar --distribution noniid --alpha 0.5 --random_cost mild_label_correlated_hierarchical --num_users 100 --concurrency 40 --buffer_size 10 --model resnet --total_rounds 150 --local_bs 100 --local_period 10 --interval 1 --lr 0.003 --algo FADAS --seed 100 --output_dir /home/jczn2/DirBridge_state/e1_runs/cifar/acc --system_metrics_log_dir /home/jczn2/DirBridge_state/e1_runs/cifar/metrics --run_tag e1_dev_fadas_t01 --global_lr 0.0001 --gpu 0
/home/jczn2/.conda/envs/yibo/bin/python main_fed.py --dataset cifar --distribution noniid --alpha 0.5 --random_cost mild_label_correlated_hierarchical --num_users 100 --concurrency 40 --buffer_size 10 --model resnet --total_rounds 150 --local_bs 100 --local_period 10 --interval 1 --lr 0.003 --algo FADAS --seed 100 --output_dir /home/jczn2/DirBridge_state/e1_runs/cifar/acc --system_metrics_log_dir /home/jczn2/DirBridge_state/e1_runs/cifar/metrics --run_tag e1_dev_fadas_t02 --global_lr 0.01 --gpu 0
/home/jczn2/.conda/envs/yibo/bin/python main_fed.py --dataset cifar --distribution noniid --alpha 0.5 --random_cost mild_label_correlated_hierarchical --num_users 100 --concurrency 40 --buffer_size 10 --model resnet --total_rounds 150 --local_bs 100 --local_period 10 --interval 1 --lr 0.003 --algo FADAS --seed 100 --output_dir /home/jczn2/DirBridge_state/e1_runs/cifar/acc --system_metrics_log_dir /home/jczn2/DirBridge_state/e1_runs/cifar/metrics --run_tag e1_dev_fadas_t03 --global_lr 0.1 --gpu 0
/home/jczn2/.conda/envs/yibo/bin/python main_fed.py --dataset cifar --distribution noniid --alpha 0.5 --random_cost mild_label_correlated_hierarchical --num_users 100 --concurrency 40 --buffer_size 10 --model resnet --total_rounds 150 --local_bs 100 --local_period 10 --interval 1 --lr 0.003 --algo FADAS --seed 100 --output_dir /home/jczn2/DirBridge_state/e1_runs/cifar/acc --system_metrics_log_dir /home/jczn2/DirBridge_state/e1_runs/cifar/metrics --run_tag e1_dev_fadas_t04 --global_lr 1.0 --gpu 0
/home/jczn2/.conda/envs/yibo/bin/python main_fed.py --dataset cifar --distribution noniid --alpha 0.5 --random_cost mild_label_correlated_hierarchical --num_users 100 --concurrency 40 --buffer_size 10 --model resnet --total_rounds 150 --local_bs 100 --local_period 10 --interval 1 --lr 0.01 --algo FADAS --seed 100 --output_dir /home/jczn2/DirBridge_state/e1_runs/cifar/acc --system_metrics_log_dir /home/jczn2/DirBridge_state/e1_runs/cifar/metrics --run_tag e1_dev_fadas_t05 --global_lr 0.0001 --gpu 0
/home/jczn2/.conda/envs/yibo/bin/python main_fed.py --dataset cifar --distribution noniid --alpha 0.5 --random_cost mild_label_correlated_hierarchical --num_users 100 --concurrency 40 --buffer_size 10 --model resnet --total_rounds 150 --local_bs 100 --local_period 10 --interval 1 --lr 0.01 --algo FADAS --seed 100 --output_dir /home/jczn2/DirBridge_state/e1_runs/cifar/acc --system_metrics_log_dir /home/jczn2/DirBridge_state/e1_runs/cifar/metrics --run_tag e1_dev_fadas_t06 --global_lr 0.01 --gpu 0
/home/jczn2/.conda/envs/yibo/bin/python main_fed.py --dataset cifar --distribution noniid --alpha 0.5 --random_cost mild_label_correlated_hierarchical --num_users 100 --concurrency 40 --buffer_size 10 --model resnet --total_rounds 150 --local_bs 100 --local_period 10 --interval 1 --lr 0.01 --algo FADAS --seed 100 --output_dir /home/jczn2/DirBridge_state/e1_runs/cifar/acc --system_metrics_log_dir /home/jczn2/DirBridge_state/e1_runs/cifar/metrics --run_tag e1_dev_fadas_t07 --global_lr 0.1 --gpu 0
/home/jczn2/.conda/envs/yibo/bin/python main_fed.py --dataset cifar --distribution noniid --alpha 0.5 --random_cost mild_label_correlated_hierarchical --num_users 100 --concurrency 40 --buffer_size 10 --model resnet --total_rounds 150 --local_bs 100 --local_period 10 --interval 1 --lr 0.01 --algo FADAS --seed 100 --output_dir /home/jczn2/DirBridge_state/e1_runs/cifar/acc --system_metrics_log_dir /home/jczn2/DirBridge_state/e1_runs/cifar/metrics --run_tag e1_dev_fadas_t08 --global_lr 1.0 --gpu 0
/home/jczn2/.conda/envs/yibo/bin/python main_fed.py --dataset cifar --distribution noniid --alpha 0.5 --random_cost mild_label_correlated_hierarchical --num_users 100 --concurrency 40 --buffer_size 10 --model resnet --total_rounds 150 --local_bs 100 --local_period 10 --interval 1 --lr 0.03 --algo FADAS --seed 100 --output_dir /home/jczn2/DirBridge_state/e1_runs/cifar/acc --system_metrics_log_dir /home/jczn2/DirBridge_state/e1_runs/cifar/metrics --run_tag e1_dev_fadas_t09 --global_lr 0.0001 --gpu 0
/home/jczn2/.conda/envs/yibo/bin/python main_fed.py --dataset cifar --distribution noniid --alpha 0.5 --random_cost mild_label_correlated_hierarchical --num_users 100 --concurrency 40 --buffer_size 10 --model resnet --total_rounds 150 --local_bs 100 --local_period 10 --interval 1 --lr 0.03 --algo FADAS --seed 100 --output_dir /home/jczn2/DirBridge_state/e1_runs/cifar/acc --system_metrics_log_dir /home/jczn2/DirBridge_state/e1_runs/cifar/metrics --run_tag e1_dev_fadas_t10 --global_lr 0.01 --gpu 0
/home/jczn2/.conda/envs/yibo/bin/python main_fed.py --dataset cifar --distribution noniid --alpha 0.5 --random_cost mild_label_correlated_hierarchical --num_users 100 --concurrency 40 --buffer_size 10 --model resnet --total_rounds 150 --local_bs 100 --local_period 10 --interval 1 --lr 0.03 --algo FADAS --seed 100 --output_dir /home/jczn2/DirBridge_state/e1_runs/cifar/acc --system_metrics_log_dir /home/jczn2/DirBridge_state/e1_runs/cifar/metrics --run_tag e1_dev_fadas_t11 --global_lr 0.1 --gpu 0
/home/jczn2/.conda/envs/yibo/bin/python main_fed.py --dataset cifar --distribution noniid --alpha 0.5 --random_cost mild_label_correlated_hierarchical --num_users 100 --concurrency 40 --buffer_size 10 --model resnet --total_rounds 150 --local_bs 100 --local_period 10 --interval 1 --lr 0.03 --algo FADAS --seed 100 --output_dir /home/jczn2/DirBridge_state/e1_runs/cifar/acc --system_metrics_log_dir /home/jczn2/DirBridge_state/e1_runs/cifar/metrics --run_tag e1_dev_fadas_t12 --global_lr 1.0 --gpu 0
/home/jczn2/.conda/envs/yibo/bin/python main_fed.py --dataset cifar --distribution noniid --alpha 0.5 --random_cost mild_label_correlated_hierarchical --num_users 100 --concurrency 40 --buffer_size 10 --model resnet --total_rounds 150 --local_bs 100 --local_period 10 --interval 1 --lr 0.01 --algo FADAS --seed 100 --output_dir /home/jczn2/DirBridge_state/e1_runs/cifar/acc --system_metrics_log_dir /home/jczn2/DirBridge_state/e1_runs/cifar/metrics --run_tag e1_dev_fadas_t13 --global_lr 0.01 --fadas_delay_adaptive --gpu 0
/home/jczn2/.conda/envs/yibo/bin/python main_fed.py --dataset cifar --distribution noniid --alpha 0.5 --random_cost mild_label_correlated_hierarchical --num_users 100 --concurrency 40 --buffer_size 10 --model resnet --total_rounds 150 --local_bs 100 --local_period 10 --interval 1 --lr 0.01 --algo FADAS --seed 100 --output_dir /home/jczn2/DirBridge_state/e1_runs/cifar/acc --system_metrics_log_dir /home/jczn2/DirBridge_state/e1_runs/cifar/metrics --run_tag e1_dev_fadas_t14 --global_lr 0.1 --fadas_delay_adaptive --gpu 0
/home/jczn2/.conda/envs/yibo/bin/python main_fed.py --dataset cifar --distribution noniid --alpha 0.5 --random_cost mild_label_correlated_hierarchical --num_users 100 --concurrency 40 --buffer_size 10 --model resnet --total_rounds 150 --local_bs 100 --local_period 10 --interval 1 --lr 0.03 --algo FADAS --seed 100 --output_dir /home/jczn2/DirBridge_state/e1_runs/cifar/acc --system_metrics_log_dir /home/jczn2/DirBridge_state/e1_runs/cifar/metrics --run_tag e1_dev_fadas_t15 --global_lr 0.01 --fadas_delay_adaptive --gpu 0
/home/jczn2/.conda/envs/yibo/bin/python main_fed.py --dataset cifar --distribution noniid --alpha 0.5 --random_cost mild_label_correlated_hierarchical --num_users 100 --concurrency 40 --buffer_size 10 --model resnet --total_rounds 150 --local_bs 100 --local_period 10 --interval 1 --lr 0.03 --algo FADAS --seed 100 --output_dir /home/jczn2/DirBridge_state/e1_runs/cifar/acc --system_metrics_log_dir /home/jczn2/DirBridge_state/e1_runs/cifar/metrics --run_tag e1_dev_fadas_t16 --global_lr 0.1 --fadas_delay_adaptive --gpu 0
/home/jczn2/.conda/envs/yibo/bin/python main_fed.py --dataset cifar --distribution noniid --alpha 0.5 --random_cost mild_label_correlated_hierarchical --num_users 100 --concurrency 40 --buffer_size 10 --model resnet --total_rounds 150 --local_bs 100 --local_period 10 --interval 1 --lr 0.003 --algo FADAS --seed 100 --output_dir /home/jczn2/DirBridge_state/e1_runs/cifar/acc --system_metrics_log_dir /home/jczn2/DirBridge_state/e1_runs/cifar/metrics --run_tag e1_dev_fadas_t17 --global_lr 1.0 --fadas_delay_adaptive --gpu 0
/home/jczn2/.conda/envs/yibo/bin/python main_fed.py --dataset cifar --distribution noniid --alpha 0.5 --random_cost mild_label_correlated_hierarchical --num_users 100 --concurrency 40 --buffer_size 10 --model resnet --total_rounds 150 --local_bs 100 --local_period 10 --interval 1 --lr 0.05 --algo FADAS --seed 100 --output_dir /home/jczn2/DirBridge_state/e1_runs/cifar/acc --system_metrics_log_dir /home/jczn2/DirBridge_state/e1_runs/cifar/metrics --run_tag e1_dev_fadas_t18 --global_lr 0.1 --gpu 0
/home/jczn2/.conda/envs/yibo/bin/python main_fed.py --dataset cifar --distribution noniid --alpha 0.5 --random_cost mild_label_correlated_hierarchical --num_users 100 --concurrency 40 --buffer_size 10 --model resnet --total_rounds 150 --local_bs 100 --local_period 10 --interval 1 --lr 0.05 --algo FADAS --seed 100 --output_dir /home/jczn2/DirBridge_state/e1_runs/cifar/acc --system_metrics_log_dir /home/jczn2/DirBridge_state/e1_runs/cifar/metrics --run_tag e1_dev_fadas_t19 --global_lr 0.1 --fadas_delay_adaptive --gpu 0
/home/jczn2/.conda/envs/yibo/bin/python main_fed.py --dataset cifar --distribution noniid --alpha 0.5 --random_cost mild_label_correlated_hierarchical --num_users 100 --concurrency 40 --buffer_size 10 --model resnet --total_rounds 150 --local_bs 100 --local_period 10 --interval 1 --lr 0.05 --algo FADAS --seed 100 --output_dir /home/jczn2/DirBridge_state/e1_runs/cifar/acc --system_metrics_log_dir /home/jczn2/DirBridge_state/e1_runs/cifar/metrics --run_tag e1_dev_fadas_t20 --global_lr 1.0 --gpu 0
